HotelReservation/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using HotelReservation.Interfaces;
using HotelReservation.Models;
using System.Xml.Linq;

namespace HotelReservation.Controllers
{
	public class CustomerController : Controller
	{
		public readonly ICustomerService _customerService;

		public CustomerController(ICustomerService costumerService)
		{
			_customerService = costumerService;
		}

		public IActionResult GetCustomers()
		{
			var AllCostumers = _customerService.GetCustomers();
			return View(AllCostumers);
		}
		
		public IActionResult SearchCustomerByName(string name)
		{
			var searchedCustomers = _customerService.SearchCustomerByName(name);
			return View("GetCustomers", searchedCustomers);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(CustomerModel category) 
		{ 
			if(ModelState.IsValid)
			{
				_customerService.CreateCustomer(category);
				return RedirectToAction("GetCustomers");
			}

			return View(category);
		}


		public IActionResult Edit(int id)
		{
			var CustomerToGet = _customerService.GetCustomer(id);
			return View(CustomerToGet);
		}


		[HttpPost]
		public IActionResult Delete(int id)
		{
			_customerService.Delete(id);
			
			return Redirect("GetCustomers");
		}

		[HttpPost]
		public IActionResult Update(CustomerModel customer)
		{
			if (ModelState.IsValid)
			{
				_customerService.UpdateCustomer(customer);
				return RedirectToAction("GetCustomers");
			}

			return View(customer);
		}
	}
}

HotelReservation/Controllers/ReservationController.cs
using HotelReservation.Entities;
using HotelReservation.Interfaces;
using HotelReservation.Models;
using HotelReservation.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Dynamic;

namespace HotelReservation.Controllers
{
	public class ReservationController : Controller
	{
		private readonly ILogger<ReservationController> _logger;
		public readonly IReservationService _reservationService;
		public readonly ICustomerService _customerService;
		public readonly IRoomService _roomService;

		public ReservationController(ILogger<ReservationController> logger, IReservationService reservationService, ICustomerService customerService, IRoomService roomService)
		{
			_roomService = roomService;
			_logger = logger;
			_reservationService = reservationService;
			_customerService = customerService;
		}
		
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}



		public IActionResult GetReservations()
		{
			var allReservations = _reservationService.GetReservations();
			return View(allReservations);
		}

        public IActionResult GetCustomers()
		{
            var AllCostumers = _customerService.GetCustomers();
            return View(AllCostumers);
        }


        public IActionResult Create()
		{
			var allCustomer = _customerService.GetCustomers();
			var allRoom = _roomService.GetRooms();

			var newReservationModel = new ReservationModel();
            newReservationModel.CustomerSelectList = new List<SelectListItem>();
            newReservationModel.RoomSelectList = new List<SelectListItem>();
			
			
			foreach (var customer in allCustomer)
			{
				newReservationModel.CustomerSelectList.Add(new SelectListItem { Text = customer.FullName, Value = customer.Id.ToString() });
			}

			foreach (var room in allRoom)
			{
				newReservationModel.RoomSelectList.Add(new SelectListItem { Text = room.RoomNumber, Value = room.Id.ToString()});
			}

            return View(newReservationModel);
		}

		[HttpPost]
		public IActionResult Create(ReservationModel reservation)
		{
			if(ModelState.IsValid)
			{
				_reservationService.CreateReservation(reservation);
                return RedirectToAction("GetReservations");
            }
			return View(reservation);

		}

		public IActionResult ShowpopUp()
		{
			var allCustomers = _customerService.GetCustomers(); 

			//specify the name or path of the partial view
			return PartialView("CustomerPopup", allCustomers);
		}

		public IActionResult Edit(int id)
		{
			var reservationToEdit = _reservationService.GetReservation(id);

			var allCustomer = _customerService.GetCustomers();
			var allRoom = _roomService.GetRooms();

			var newReservationModel = new ReservationModel();
			newReservationModel.CustomerSelectList = new List<SelectListItem>();
			newReservationModel.RoomSelectList = new List<SelectListItem>();

			foreach (var customer in allCustomer)
			{

				newReservationModel.CustomerSelectList.Add(new SelectListItem { Text = customer.FullName, Value = customer.Id.ToString() });
			}

			foreach (var room in allRoom)
			{
				newReservationModel.RoomSelectList.Add(new SelectListItem { Text = room.RoomNumber, Value = room.Id.ToString() });
			}

			ViewBag.NewReservationModel = newReservationModel;
			/*ViewBag.reservationToEdit = reservationToEdit;*/

			return View(reservationToEdit);
		}
		public IActionResult Update(ReservationModel reservation)
		{
			if(ModelState.IsValid)
			{
				_reservationService.UpdateReservation(reservation);
				return RedirectToAction("GetReservations");
			}

			return View(reservation);
		}
	


	}
}

HotelReservation/Controllers/RoomController.cs
using HotelReservation.Interfaces;
using HotelReservation.Models;
using HotelReservation.Services;
using Microsoft.AspNetCore.Mvc;

namespace HotelReservation.Controllers
{
	public class RoomController : Controller
	{
		public readonly IRoomService _roomService;

		public RoomController(IRoomService roomService)
		{
			_roomService = roomService;
		}

		public IActionResult GetRooms()
		{
			var AllRooms = _roomService.GetRooms();
			return View(AllRooms);
		}

		public IActionResult GetRoomsByNumber(string name)
		{
			var SearchedRooms = _roomService.GetRoomsByNumber(name);
			return View("GetRooms", SearchedRooms);
		}


		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(RoomModel room)
		{
			if (ModelState.IsValid)
			{
				_roomService.CreateRoom(room);
				return RedirectToAction("GetRooms");
			}

			return View(room);
		}

		public IActionResult Edit(int id)
		{
			var SelectedRoom = _roomService.GetRoom(id);
			return View(SelectedRoom);
		}

		[HttpPost]
		public IActionResult Update(RoomModel room)
		{
			if (ModelState.IsValid)
			{
				_roomService.UpdateRoom(room);
				return RedirectToAction("GetRooms");
			}

			return View(room);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
			_roomService.DeleteRoom(id);
			return RedirectToAction("GetRooms");
		}
	}
}

HotelReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelReservation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelReservation.styles.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="~/css/PageDesignes.css asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Reservation" asp-action="GetReservations">HotelReservation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="GetReservations">Reservations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="GetCustomers">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="GetRooms">Rooms</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container" style="margin:0; max-width:none;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HotelReservation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>